config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :devices
    get :autocomplete_user_username, :on => :collection
  end

  resources :devices do
    get :autocomplete_device_serial_number, :on => :collection
  end

  get 'access/login' => 'access#login'
  get 'access/attempt_login' => 'access#attempt_login'
  post 'access/attempt_login' => 'access#attempt_login'
  get 'access/logout' => 'access#logout'

  root 'access#login'

end

app/models/device.rb
class Device < ActiveRecord::Base

  belongs_to :user

  scope :sorted, lambda { order("serial_number ASC")}

  validates :serial_number, presence: true

  def self.search(query)
    where("serial_number ILIKE :query OR device_type ILIKE :query", query: "%#{query}%")
end


end

app/models/user.rb
class User < ActiveRecord::Base

  scope :sorted, lambda { order("last_name ASC, first_name ASC")}

  has_secure_password validations: false

  has_many :devices

#  validates_presence_of :password, :on => :create
#  validates_presence_of :password_confirmation
#  validates_confirmation_of :password

  validates :first_name, :presence => true, :length => { :maximum => 25 }
  validates :last_name, :presence => true, :length => { :maximum => 50 }
  validates :username, :presence => true, :length => { :within => 4..25 }, :uniqueness => true

  def name
    "#{first_name} #{last_name}"
  end

  def self.search(query)
    #where("username ILIKE ?", "%#{query}%")
    where('username ILIKE :query OR first_name ILIKE :query OR last_name ILIKE :query', query: "%#{query}%")
  end

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

  def index
    @username = params[:username]
  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
      session[:first_name] = authorized_user.first_name
      session[:last_name] = authorized_user.last_name
      flash[:notice] = "You are now logged in as #{session[:first_name]} #{session[:last_name]}"
      redirect_to users_path
    else
      flash[:notice] = "Invalid username/password combination"
      redirect_to access_login_path
    end

  end

  def logout
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = "Logged out"
    redirect_to access_login_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def confirm_logged_in
    unless session[:user_id]
      redirect_to(:controller => 'access', :action => 'login')
      return false
    else
      return true
    end
  end

  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end

  def user_admin
    redirect_to(access_login_path) unless current_user && current_user.admin == true
  end

  def correct_user
    @user = User.find(params[:id])
    unless user_admin
      redirect_to(access_login_path) unless @user == current_user
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  autocomplete :device, :serial_number

  before_action :find_user
  before_action :confirm_logged_in
  before_action :user_admin, except: [:index, :show]

  def index
    respond_to do |format|
      format.html
      format.json { @devices = Device.search(params[:search]) }
    end
  end

  def show
    @device = Device.find(params[:id])
  end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(device_params)

    if @device.save
      redirect_to device_path(@device)
    else
      render 'new'
    end
  end

  def edit
    @device = Device.find(params[:id])
  end

  def update
    @device = Device.find(params[:id])

    if @device.update_attributes(device_params)
      redirect_to device_path(@device)
    else
      render 'edit'
    end
  end

  def delete
    @device = Device.find(params[:id])
  end

  def destroy
    @device = Device.find(params[:id])
    @device.destroy
    redirect_to devices_path
  end

  private

  def device_params
    params.require(:device).permit(:serial_number, :user_id, :device_type)
  end

  def find_user
    if params[:search]
      @devices = Device.search(params[:search]).paginate(page: params[:page], :per_page => 15)
    elsif params[:user_id]
      @devices = Device.where(user_id: params[:user_id]).paginate(page: params[:page], :per_page => 15)
    else
      @devices = Device.all.paginate(page: params[:page], :per_page => 15)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  autocomplete :user, :username, :extra_data => [:first_name, :last_name]

  before_action :confirm_logged_in
  before_action :user_admin, except: [:show, :index]
  #before_action :correct_user, only: [:edit, :update, :show]


  def index
    if params[:search]
      @users = User.search(params[:search]).sorted.paginate(page: params[:page], :per_page => 15)
    else
      @users = User.all.sorted.paginate(page: params[:page], :per_page => 15)
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation, :admin)
  end

end

app/helpers/access_helper.rb
module AccessHelper
  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  
  def user_admin?
    current_user.admin == true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<div class="login">
  <%= form_tag(:action => 'attempt_login') do %>
    <table>
      <tr>
        <th><%= label_tag(:username) %></th>
        <td><%= text_field_tag(:username) %></td>
      </tr>
      <tr>
        <th><%= label_tag(:password) %></th>
        <td><%= password_field_tag(:password) %></td>
      </tr>

      <tr>
        <th>&nbsp;</th>
        <td><%= submit_tag("Log In", class: 'btn btn-inverse') %></td>
      </tr>
    </table>
    <hr>
  <% end %>
</div>

app/views/devices/_device.html.erb
<% if device.user %>
  <h2><%= "#{device.user.name.possessive} #{device.device_type}" %></h2>
<% else %>
  <h2>Device</h2>
<% end %>

<table class="table-condensed">
  <tr>
    <th>Serial Number: </th>
    <td><%= device.serial_number %></td>
  </tr>

  <tr>
    <th>Device Type: </th>
    <td><%= device.device_type %></td>
  </tr>

  <tr>
    <th>Assigned User: </th>
    <% if device.user %>
      <td><%= link_to device.user.name, user_path(device.user) %></td>
    <% else %>
      <td>No Assigned User</td>
    <% end %>
  </tr>
</table>

app/views/devices/_form.html.erb
<table class="table-condensed">
  <tr>
    <th><%= f.label :serial_number %></th>
    <td><%= f.text_field :serial_number %></td>
  </tr>
  <tr>
    <th><%= f.label :user_id %></th>
    <td><%= f.text_field :user_id %></td>
  </tr>
  <tr>
    <th><%= f.label :device_type, "Device Type" %></th>
    <td><%= f.text_field :device_type %></td>
  </tr>
</table>

app/views/devices/edit.html.erb
<%= form_for @device do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit("Update Device", class: 'btn btn-inverse') %>
<% end %>

app/views/devices/index.html.erb
<h2>Devices</h2>
<% if user_admin? %>
  <%= button_to "New Device", new_device_path, method: 'get', class: 'btn btn-inverse', id: 'new-button' %>
<% end %>

<div class="row.fluid">
  <div class="col-sm-4">
    <%= form_tag(devices_path, method: 'get', id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search for username...", autofocus: true %>
      <%#= autocomplete_field_tag :search, '', autocomplete_device_serial_number_devices_path, placeholder: "Search for serial number...", autofocus: true %>
      <%= submit_tag "Search", class: 'btn btn-inverse', name: nil %>
    <% end %>

  </div>

  <div class="col-sm-8" id="pages">
        <div class="digg_pagination">
      <%= will_paginate @users%>
    </div>
  </div>
<hr>
<br>



<table class="table">
  <tr>
    <th>Serial Number </th>
    <th>Assigned User</th>
    <th>Device Type</th>
    <% if user_admin? %>
      <th>Actions</th>
    <% end %>
  </tr>

  <% @devices.each do |f| %>
  <tr>
    <td><%= link_to f.serial_number.upcase, device_path(f) %></td>
    <td>
      <% if f.user %>
        <%= link_to f.user.name, user_path(f.user) %>
      <% else %>
        No assigned user
      <% end %>
    </td>
    <td><%= f.device_type %></td>
    <% if user_admin? %>
      <td>
        <%= link_to "Edit", edit_device_path(f) %>
        <%= link_to "Delete", f, method: :delete %>
      </td>
    <% end %>
  <% end %>
  </tr>
</table>

<div class="digg_pagination" id="pages">
  <%= will_paginate @users%>
</div>

app/views/devices/new.html.erb
<h2>New Device</h2>
<%= form_for @device do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit('Create Device', class: 'btn btn-inverse') %>
<% end %>

app/views/devices/show.html.erb
<%= render partial: 'device', locals: { device: @device } %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">

        <% if logged_in? %>
          <li class="navbar-brand active"><%= link_to_unless_current "#{current_user.first_name} #{current_user.last_name}", user_path(current_user), id: "brandname" %></li>
        <% else %>
          <li class="navbar-brand active">Inventory</li>
        <% end %>
    </div>
    <div class="nav navbar-nav">
      <li class="active"><%= link_to "Users", users_path %></li>
      <li class="active"><%= link_to "Devices", devices_path %></li>
      <% if logged_in? %>
        <li class="active"><%= link_to "Logout", access_logout_path %></li>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/navigation' %>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<table class="table-condensed">
  <tr>
    <th><%= f.label(:first_name) %></th>
    <td><%= f.text_field(:first_name) %></td><br>
  </tr>
  <tr>
    <th><%= f.label(:last_name) %></th>
    <td><%= f.text_field(:last_name) %></td><br>
  </tr>
  <tr>
      <th><%= f.label(:username) %></th>
      <td><%= f.text_field(:username) %></td><br>
  </tr>
  <tr>
      <th><%= f.label(:password) %></th>
      <td><%= f.password_field(:password) %></td>
  </tr>
  <tr>
    <th><%= f.label(:confirm) %></th>
    <td><%= f.password_field(:password_confirmation) %></td>
  </tr>
</table>

app/views/users/_user.html.erb
<h2><%= user.name %></h2>

<table class="table-bordered">
  <tr>
    <th>Assigned devices:</th>
  </tr>
  <% user.devices.each do |f| %>
    <tr>
      <td><%= link_to f.serial_number.upcase, device_path(f) %></td>
    </tr>
  <% end %>
</table>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit("Update User", class: 'btn btn-inverse') %>
<% end %>

app/views/users/index.html.erb
<h2>Users</h2>
<% if user_admin? %>
  <%= button_to "New User", new_user_path, method: 'get', class: 'btn btn-inverse'%>
<% end %>
<div class="row.fluid">
  <div class="col-sm-4">
    <%= form_tag(users_path, method: 'get', id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search for username...", autofocus: true %>
      <%#= autocomplete_field_tag :search, '', autocomplete_user_username_users_path, placeholder: "Search for username...", autofocus: true %>
      <%= submit_tag "Search", class: 'btn btn-inverse', :name => nil %>
    <% end %>
  </div>
  <div class="col-sm-8" id="pages">

    <div class="digg_pagination">
      <%= will_paginate @users%>
    </div>
  </div>
<hr>
<br>

<table class="table">
  <tr>
    <th>Name </th>
    <th>Devices Assigned</th>
    <% if user_admin? %>
      <th>Actions</th>
    <% end %>
  </tr>

  <% @users.each do |f| %>
  <tr>
    <td><%= link_to f.name, user_path(f) %> </td>
    <td><%= link_to f.devices.size, user_devices_path(f) %></td>
    <% if user_admin? %>
      <td>
        <%= link_to "Edit", edit_user_path(f) %>
        <%= link_to "Delete", f, method: :delete %>
      </td>
    <% end %>
  <% end %>
  </tr>

</table>
<div class="digg_pagination" id="pages">
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<h2>New User</h2>
<%= form_for @user do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit('Create User', class: 'btn btn-inverse') %>
<% end %>

app/views/users/show.html.erb
<%= render partial: 'user', locals: { user: @user } %>